name: Production App CD with Maven

on:
  push:
    branches: [ "master" ]

env:
  BRANCH_NAME: ${{github.ref_name}}
  APP_NAME: tech-challenge-fiap-production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout    
      uses: actions/checkout@v3

    - name: Check Branch Name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Create Docker Tag
      run: |
        if [[ ${{env.BRANCH_NAME}} == 'master' ]]
        then
          DOCKER_TAG="latest-${{ github.sha }}"
        else
          DOCKER_TAG="${{env.BRANCH_NAME}}-latest-${{ github.sha }}"
        fi
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    - name: Check Docker Tag
      run: echo ${{ env.DOCKER_TAG }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build and Push to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: "i2f8d1v7"
        REPOSITORY: ${{ env.APP_NAME }}
        IMAGE_TAG: ${{ env.DOCKER_TAG }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
